# ============================================================
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS builder

WORKDIR /src

ADD . .

RUN dotnet restore \
&& dotnet publish -c Release -o /dist

# ============================================================
FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS runner

ARG BASE_DIR=/workspace/www/hangfire-container/server

WORKDIR ${BASE_DIR}

COPY --from=builder /dist .

RUN chown 1000:1000 -R ${BASE_DIR}

VOLUME ${BASE_DIR}"/appsettings.Production.yaml"

EXPOSE 80

CMD ["dotnet", "HangfireContainer.Server.dll"]
